services:
  postgres:
    image: postgres:15
    container_name: postgresMiniMarket
    environment:
      POSTGRES_USER: minimarket
      POSTGRES_PASSWORD: minimarket.ps
      POSTGRES_DB: mini_market_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_new:/var/lib/postgresql/data

volumes:
  postgres_data_new:
